<a href="https://colab.research.google.com/github/Kacper-W-Kozdon/notebook-testing-ivy/blob/main/ivy_paddle_bfw_grad_issue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install paddlepaddle
import paddle as paddle
import torch
import tensorflow as tf

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.7/125.7 MB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 10.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 9.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 6.9 MB/s eta 0:00:00


In [ ]:
paddle.disable_static()
x = paddle.to_tensor([[[[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-1.39360240e-01]]],

                    [[[-1.38816263e-01]],
                     [[-3.42670618e+03]],
                     [[-3.22831575e+01]],
                     [[-5.45454544e+03]],
                     [[-1.10000000e+00]]],

                    [[[-1.10000000e+00]],
                     [[-2.00001000e+00]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]]],

                    [[[ 2.79699967e-01]],
                     [[ 1.00000000e+00]],
                     [[ 3.33333333e-01]],
                     [[ 1.00000000e-04]],
                     [[ 9.09090909e+03]]]])
x.stop_gradient = False
axis = [0, 2]
keepdims = False
y = paddle.amax(
            paddle.sum(paddle.abs(x), axis=axis[0], keepdim=True),
            axis=axis,
            keepdim=keepdims,
        )
y.stop_gradient = False
z = paddle.grad(y, x)
z = paddle.to_tensor(z)
print(y)
print(x.shape, y.shape, z.shape, z)

Tensor(shape=[5, 1], dtype=float32, place=Place(cpu), stop_gradient=False,
       [[257.51852417 ],
        [3685.70629883],
        [289.61648560 ],
        [5711.54541016],
        [9093.14843750]])
[4, 5, 1, 1] [5, 1] [1, 4, 5, 1, 1] Tensor(shape=[1, 4, 5, 1, 1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[[[[ 0.00000000]],

          [[-0.00000000]],

          [[-0.00000000]],

          [[-0.00000000]],

          [[ 0.00000000]]],


         [[[ 0.00000000]],

          [[-0.00000000]],

          [[-0.00000000]],

          [[-0.00000000]],

          [[ 0.00000000]]],


         [[[ 0.00000000]],

          [[-0.00000000]],

          [[-0.00000000]],

          [[-0.00000000]],

          [[ 0.00000000]]],


         [[[-0.00000000]],

          [[ 0.00000000]],

          [[ 0.00000000]],

          [[ 0.00000000]],

          [[-0.00000000]]]]])


In [8]:
paddle.disable_static()
x = paddle.to_tensor([[[[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-1.39360240e-01]]],

                    [[[-1.38816263e-01]],
                     [[-3.42670618e+03]],
                     [[-3.22831575e+01]],
                     [[-5.45454544e+03]],
                     [[-1.10000000e+00]]],

                    [[[-1.10000000e+00]],
                     [[-2.00001000e+00]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]]],

                    [[[ 2.79699967e-01]],
                     [[ 1.00000000e+00]],
                     [[ 3.33333333e-01]],
                     [[ 1.00000000e-04]],
                     [[ 9.09090909e+03]]]])
x.stop_gradient = False
axis = [0, 2]
keepdims = False
y = paddle.amax(
            paddle.sum(paddle.abs(x), axis=axis[0], keepdim=True),
            axis=axis,
            keepdim=keepdims,
        )
y.stop_gradient = False
z = paddle.grad(y, x)
z = paddle.to_tensor(z)
print(x.shape, y.shape, z.shape, z)

[4, 5, 1, 1] [5, 1] [1, 4, 5, 1, 1] Tensor(shape=[1, 4, 5, 1, 1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[[[[ 28.66020393]],

          [[-0.00000000 ]],

          [[ -0.        ]],

          [[ -0.        ]],

          [[ -0.        ]]],


         [[[ 28.66020393]],

          [[-0.00000000 ]],

          [[ -0.        ]],

          [[ -0.        ]],

          [[ -0.        ]]],


         [[[ 28.66020393]],

          [[-0.00000000 ]],

          [[ -0.        ]],

          [[ -0.        ]],

          [[ -0.        ]]],


         [[[-28.66020393]],

          [[ 0.00000000 ]],

          [[ 0.         ]],

          [[ 0.         ]],

          [[ 0.         ]]]]])


In [ ]:
x = torch.tensor([[[[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-1.39360240e-01]]],

                    [[[-1.38816263e-01]],
                     [[-3.42670618e+03]],
                     [[-3.22831575e+01]],
                     [[-5.45454544e+03]],
                     [[-1.10000000e+00]]],

                    [[[-1.10000000e+00]],
                     [[-2.00001000e+00]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]]],

                    [[[ 2.79699967e-01]],
                     [[ 1.00000000e+00]],
                     [[ 3.33333333e-01]],
                     [[ 1.00000000e-04]],
                     [[ 9.09090909e+03]]]])
x.requires_grad_(True)
axis = (0, 2)
ord = 1
keepdims = False
y = torch.linalg.matrix_norm(x, dim=axis, keepdims=keepdims, ord=ord)
y=y.expand((4, 5, 1))
w = torch.gradient(y, dim=(0,))
print(w[0])

tensor([[[0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.]]], grad_fn=<CatBackward0>)


In [68]:
x = torch.tensor([[[-1.], [-1.]]])
x.requires_grad_(True)
axis = (0, 2)
ord = -1
keepdims = False
y = torch.linalg.matrix_norm(x, dim=axis, keepdims=keepdims, ord=ord)
print(y)
y.backward(inputs=x, gradient=torch.tensor([1, 1]))
print(x.grad)

tensor([1., 1.], grad_fn=<AminBackward0>)
tensor([[[-1.],
         [-1.]]])


In [45]:
x = torch.tensor([3.])
x.requires_grad_(True)
y = x**2
y.backward(inputs=x)
print(x.grad)

tensor([6.])


In [67]:
paddle.disable_static()
x = paddle.to_tensor([[[-1.], [-1.]]])
x.stop_gradient = False
axis = [0, 2]
axis_ = [0, 2]
keepdims = False
x = paddle.moveaxis(x, axis_, [-2, -1])
y = paddle.min(
            paddle.linalg.svd(x)[1],
            axis=-1,
            keepdim=False,
        )
y.stop_gradient = False
z = paddle.grad(y, x)
z = paddle.to_tensor(z)
print(x.shape, y.shape, z.shape, z)

[2, 1, 1] [2] [1, 2, 1, 1] Tensor(shape=[1, 2, 1, 1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[[[-1.]],

         [[-1.]]]])
