<a href="https://colab.research.google.com/github/Kacper-W-Kozdon/notebook-testing-ivy/blob/main/ivy_paddle_bfw_grad_issue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
!pip install paddlepaddle
import paddle as paddle
import torch
import tensorflow as tf

In [ ]:
paddle.disable_static()
x = paddle.to_tensor([[[[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-1.39360240e-01]]],

                    [[[-1.38816263e-01]],
                     [[-3.42670618e+03]],
                     [[-3.22831575e+01]],
                     [[-5.45454544e+03]],
                     [[-1.10000000e+00]]],

                    [[[-1.10000000e+00]],
                     [[-2.00001000e+00]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]]],

                    [[[ 2.79699967e-01]],
                     [[ 1.00000000e+00]],
                     [[ 3.33333333e-01]],
                     [[ 1.00000000e-04]],
                     [[ 9.09090909e+03]]]])
x.stop_gradient = False
axis = [0, 2]
keepdims = True
y = paddle.max(
            paddle.sum(paddle.abs(x), axis=axis[0], keepdim=True),
            axis=axis,
            keepdim=keepdims,
        )
y.stop_gradient = False
z = paddle.grad(y, x)
z = paddle.to_tensor(z)
print(y)
print(x.shape, y.shape, z.shape, z)

Tensor(shape=[1, 5, 1, 1], dtype=float32, place=Place(cpu), stop_gradient=False,
       [[[[257.51852417 ]],

         [[3685.70629883]],

         [[289.61648560 ]],

         [[5711.54541016]],

         [[9093.14843750]]]])
[4, 5, 1, 1] [1, 5, 1, 1] [1, 4, 5, 1, 1] Tensor(shape=[1, 4, 5, 1, 1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[[[[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]]],


         [[[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]]],


         [[[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]]],


         [[[ 1.]],

          [[ 1.]],

          [[ 1.]],

          [[ 1.]],

          [[ 1.]]]]])


In [117]:
paddle.disable_static()
x = paddle.to_tensor([[[[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-1.39360240e-01]]],

                    [[[-1.38816263e-01]],
                     [[-3.42670618e+03]],
                     [[-3.22831575e+01]],
                     [[-5.45454544e+03]],
                     [[-1.10000000e+00]]],

                    [[[-1.10000000e+00]],
                     [[-2.00001000e+00]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]]],

                    [[[ 2.79699967e-01]],
                     [[ 1.00000000e+00]],
                     [[ 3.33333333e-01]],
                     [[ 1.00000000e-04]],
                     [[ 9.09090909e+03]]]])
x.stop_gradient = False
axis = [0, 2]
keepdims = False
y = paddle.max(
            paddle.sum(paddle.abs(x), axis=axis[0], keepdim=True),
            axis=axis,
            keepdim=keepdims,
        )
y.stop_gradient = False
z = paddle.grad(y, x)
z = paddle.to_tensor(z)
print(x.shape, y.shape, z.shape, z)
print()
print(paddle.sum(paddle.abs(x), axis=axis[0], keepdim=True))

[4, 5, 1, 1] [5, 1] [1, 4, 5, 1, 1] Tensor(shape=[1, 4, 5, 1, 1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[[[[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]]],


         [[[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]]],


         [[[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]],

          [[-1.]]],


         [[[ 1.]],

          [[ 1.]],

          [[ 1.]],

          [[ 1.]],

          [[ 1.]]]]])

Tensor(shape=[1, 5, 1, 1], dtype=float32, place=Place(cpu), stop_gradient=False,
       [[[[257.51852417 ]],

         [[3685.70629883]],

         [[289.61648560 ]],

         [[5711.54541016]],

         [[9093.14843750]]]])


In [113]:
x = torch.tensor([[[[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-1.39360240e-01]]],

                    [[[-1.38816263e-01]],
                     [[-3.42670618e+03]],
                     [[-3.22831575e+01]],
                     [[-5.45454544e+03]],
                     [[-1.10000000e+00]]],

                    [[[-1.10000000e+00]],
                     [[-2.00001000e+00]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]]],

                    [[[ 2.79699967e-01]],
                     [[ 1.00000000e+00]],
                     [[ 3.33333333e-01]],
                     [[ 1.00000000e-04]],
                     [[ 9.09090909e+03]]]])
v = torch.tensor([[[[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-2.56000000e+02]],
                     [[-1.39360240e-01]]],

                    [[[-1.38816263e-01]],
                     [[-3.42670618e+03]],
                     [[-3.22831575e+01]],
                     [[-5.45454544e+03]],
                     [[-1.10000000e+00]]],

                    [[[-1.10000000e+00]],
                     [[-2.00001000e+00]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]],
                     [[-9.99990000e-01]]],

                    [[[ 2.79699967e-01]],
                     [[ 1.00000000e+00]],
                     [[ 3.33333333e-01]],
                     [[ 1.00000000e-04]],
                     [[ 9.09090909e+03]]]])
v.requires_grad_(True)
x.requires_grad_(True)
axis = (0, 2)
ord = 1
keepdims = False
y = torch.linalg.matrix_norm(x, dim=axis, keepdims=keepdims, ord=ord)
print(y)
y.backward(torch.ones_like(y))
print(x.grad)
z = torch.amax(torch.sum(torch.abs(v), axis=axis[0], keepdim=True), axis=axis, keepdim=keepdims)
z.backward(torch.ones_like(z))
print(all(v.grad.flatten() == x.grad.flatten()))

tensor([[ 257.5185],
        [3685.7063],
        [ 289.6165],
        [5711.5454],
        [9093.1484]], grad_fn=<AmaxBackward0>)
tensor([[[[-1.]],

         [[-1.]],

         [[-1.]],

         [[-1.]],

         [[-1.]]],


        [[[-1.]],

         [[-1.]],

         [[-1.]],

         [[-1.]],

         [[-1.]]],


        [[[-1.]],

         [[-1.]],

         [[-1.]],

         [[-1.]],

         [[-1.]]],


        [[[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]],

         [[ 1.]]]])
True


In [121]:
x = torch.tensor([[[-1.], [-1.]]])
x.requires_grad_(True)
axis = (0, 1)
ord = -1
keepdims = False
y = torch.linalg.matrix_norm(x, dim=axis, keepdims=keepdims, ord=ord)
print(y)
y.backward(torch.ones_like(y))
print(x.grad)

tensor([1.], grad_fn=<AminBackward0>)
tensor([[[-0.5000],
         [-0.5000]]])


In [88]:
paddle.disable_static()
axis = [0, 2]
x = paddle.to_tensor([[[-1.], [-1.]]])
x.stop_gradient=False
x = paddle.moveaxis(x, axis, [-2, -1])
ret = paddle.min(paddle.linalg.svd(x)[1], axis=-1, keepdim=False)
grad = paddle.grad(ret, x)
grad = paddle.to_tensor(grad)
print(ret)
print(grad)

Tensor(shape=[2], dtype=float32, place=Place(cpu), stop_gradient=False,
       [1., 1.])
Tensor(shape=[1, 2, 1, 1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[[[-1.]],

         [[-1.]]]])


In [108]:
x = torch.tensor([5.])
x.requires_grad_(True)
y = x**3
y.backward(gradient=torch.ones_like(y))
print(x.grad)

tensor([75.])


In [37]:
paddle.disable_static()
x = paddle.to_tensor([[-1.]])
x.stop_gradient = False
axis = [0, 1]
axis_ = [0, 1]
print(x.dim())
keepdims = False
x = paddle.moveaxis(x, axis_, [-2, -1])
y = paddle.amin(
            paddle.linalg.svd(x)[1],
            axis=0,
            keepdim=False,
        )
y.stop_gradient = False
z = paddle.grad(y, x)
z = paddle.to_tensor(z)
print(x.shape, y.shape, z.shape, "\n", z)

2
[1, 1] [] [1, 1, 1] 
 Tensor(shape=[1, 1, 1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[[-1.]]])


In [125]:
paddle.disable_static()
x = paddle.to_tensor([[[-1.], [-1.]]])
x.stop_gradient = False
axis = [0, 1]
keepdims = False
y = paddle.amax(
            paddle.sum(paddle.abs(x), axis=axis[0], keepdim=True),
            axis=axis,
            keepdim=keepdims,
        )
y.stop_gradient = False
z = paddle.grad(y, x)
z = paddle.to_tensor(z)
print(x.shape, y.shape, z.shape, z)
print()
print(paddle.sum(paddle.abs(x), axis=axis[0], keepdim=True))

[1, 2, 1] [1] [1, 1, 2, 1] Tensor(shape=[1, 1, 2, 1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[[[-0.50000000],
          [-0.50000000]]]])

Tensor(shape=[1, 2, 1], dtype=float32, place=Place(cpu), stop_gradient=False,
       [[[1.],
         [1.]]])


In [35]:
paddle.disable_static()
axis = [0, 1]
x = paddle.to_tensor([[[-1., -1.]]])
x.stop_gradient=False
x = paddle.moveaxis(x, axis, [-2, -1])
ret = paddle.amin(paddle.linalg.svd(x)[1], axis=0,)
grad = paddle.grad(ret, x)
grad = paddle.to_tensor(grad)
print(ret)
print(grad)

Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=False,
       [1.])
Tensor(shape=[1, 2, 1, 1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[[[-0.50000000]],

         [[-0.50000000]]]])
