<a href="https://colab.research.google.com/github/Kacper-W-Kozdon/notebook-testing-ivy/blob/main/testing_ivy_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import shutil

In [1]:
!pip install paddlepaddle

In [2]:
import torch as torch
import paddle as paddle
import tensorflow as tf

In [1]:
!git clone -b core_matrix_norm https://github.com/Kacper-W-Kozdon/ivy.git

Cloning into 'ivy'...
remote: Enumerating objects: 188440, done.
remote: Counting objects: 100% (176/176), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 188440 (delta 104), reused 75 (delta 58), pack-reused 188264
Receiving objects: 100% (188440/188440), 164.08 MiB | 11.74 MiB/s, done.
Resolving deltas: 100% (151803/151803), done.


In [2]:
import ivy

In [3]:
!pip install ivy

!git clone -b core_matrix_norm https://github.com/Kacper-W-Kozdon/ivy.git
import ivy

fatal: destination path 'ivy' already exists and is not an empty directory.


In [ ]:
ivy.set_backend("paddle")
x = ivy.native_array([[[-1.], [-1.]]], dtype = "float32")
dtype = "float64"
x = x.astype(dtype)
keepdims = False
ord = -2
axis = (0, 2)

paddle_matrix_norm = ivy.linalg.matrix_norm(x, keepdims=keepdims, ord=ord, axis=axis)
def func_paddle(x):
  return ivy.linalg.matrix_norm(x, keepdims=keepdims, ord=ord, axis=axis)
print(func_paddle(x))
ret, grad = ivy.execute_with_gradients(func_paddle, x, retain_grads=True)
print(grad)

ivy.array([1., 1.])
[]


In [ ]:
ivy.set_backend("torch")
x = ivy.native_array([[[-1.], [-1.]]], dtype = "float32")
dtype = torch.float64
keepdims = False
ord = -2
axis = (0, 2)

torch_matrix_norm = ivy.linalg.matrix_norm(x, keepdims=keepdims, dtype=dtype, ord=ord, axis=axis)
def func_torch(x):
  return ivy.linalg.matrix_norm(
      x, keepdims=keepdims, axis=axis, ord=ord, dtype=dtype)
print(func_torch(x))
ret, grad = ivy.execute_with_gradients(func_torch, x, retain_grads=True)
print(ret, grad)

ivy.array([1., 1.])
ivy.array([1., 1.]) []


In [ ]:
ivy.set_backend("torch")
x = ivy.native_array([[[-1.], [-1.]]], dtype = "float32")
dtype = torch.float64
keepdims = False
ord = -2
axis = (0, 2)
x.requires_grad_(True)
def func_torch(x):
  return x**2
print(func_torch(x))
ret, grad = ivy.execute_with_gradients(func_torch, x, retain_grads=True)
print(ret, grad)
func_torch(x).backward(gradient=torch.ones(x.shape))
print(x.grad)

tensor([[[1.],
         [1.]]], grad_fn=<PowBackward0>)
ivy.array([[[1.],
        [1.]]]) []
tensor([[[-2.],
         [-2.]]])


In [ ]:
ivy.set_backend("tensorflow")
x = ivy.native_array([[[-1.], [-1.]]], dtype = "float32")
dtype = tf.float64
keepdims = False
ord = -2
axis = (0, 2)

torch_matrix_norm = ivy.linalg.matrix_norm(x, keepdims=keepdims, dtype=dtype, ord=ord, axis=axis)
def func_tf(x):
  return ivy.linalg.matrix_norm(x, keepdims=keepdims, axis=axis, ord=ord, dtype=dtype)
print(func_tf(x))
ret, grad = ivy.execute_with_gradients(func_tf, x, retain_grads=True)
print(ret, grad)

ivy.array([1., 1.])
ivy.array([1., 1.]) ivy.array([[[-1.],
        [-1.]]])


In [ ]:
ivy.set_backend("tensorflow")
x = ivy.native_array([[[-1.], [-1.]]], dtype = "float32")
dtype = tf.float64

def func_tf(x):
  return x**2
print(func_tf(x))
ret, grad = ivy.execute_with_gradients(func_tf, x, retain_grads=True)
print(ret, grad)

tf.Tensor(
[[[1.]
  [1.]]], shape=(1, 2, 1), dtype=float32)
ivy.array([[[1.],
        [1.]]]) ivy.array([[[-2.],
        [-2.]]])


In [ ]:

def func_torch_bfw():
  keepdims = False
  ord = 2
  axis = (0, 2)
  x = torch.tensor([[[-1.], [-1.]]])
  x.requires_grad_(True)
  y = torch.linalg.matrix_norm(x, ord=ord, keepdims=keepdims, axis=axis)
  print(y)
  y.backward(inputs=x, gradient=torch.ones(y.shape))
  return x.grad
func_torch_bfw()


tensor([1., 1.], grad_fn=<AmaxBackward0>)


tensor([[[-1.],
         [-1.]]])

In [ ]:
@tf.function
def example():
  x = tf.constant([[[-1.], [-1.]]])

  ord = 2
  axis = (0, 2)
  keepdims=False
  y = tf.linalg.norm(x, ord=ord, axis=axis, keepdims=keepdims)
  g = tf.gradients(y, x)
  return g
example()



[<tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
 array([[[-1.],
         [-1.]]], dtype=float32)>]

In [4]:
ivy.set_backend("paddle")
x = ivy.array([[[-1.], [-1.]]], dtype = "float32")
dtype = torch.float64
keepdims = False
ord = -2
axis = (0, 2)
func = lambda x: ivy.linalg.matrix_norm(x, keepdims=keepdims, ord=ord, axis=axis)
func_ret = ivy.execute_with_gradients(func, x, retain_grads=True)
print(func_ret)


/usr/local/lib/python3.10/dist-packages/ivy/utils/exceptions.py:383: UserWarning: The current backend: 'paddle' does not support inplace updates natively. Ivy would quietly create new arrays when using inplace updates with this backend, leading to memory overhead (same applies for views). If you want to control your memory management, consider doing ivy.set_inplace_mode('strict') which should raise an error whenever an inplace update is attempted with this backend.
  warnings.warn(


(ivy.array([1., 1.]), [])


In [ ]:
ivy.set_backend("paddle")
x = ivy.array([[[-1.], [-1.]]], dtype = "float32")

func = lambda x: x**2
func_ret = ivy.execute_with_gradients(func, x, retain_grads=True)
print(func_ret)

(ivy.array([[[1.],
        [1.]]]), [])


In [40]:
ivy.set_backend("tensorflow")
x = ivy.array([[[-2.], [-1.]]])

def func_tf(x):
  return x**3
ret_tf, grad_tf = ivy.execute_with_gradients(func_tf, x)
print(f"Tensorflow: \nret = {ret_tf}, \ngrad = {grad_tf}")

print("\n")

ivy.set_backend("torch")
y = ivy.array([[[-2.], [-1.]]])

def func_torch(y):
  return y**3
ret_torch, grad_torch = ivy.execute_with_gradients(func_torch, y)
print(f"Torch: \nret = {ret_torch}, \ngrad = {grad_torch}")

Tensorflow: 
ret = ivy.array([[[-8.],
        [-1.]]]), 
grad = ivy.array([[[12.],
        [ 3.]]])


Torch: 
ret = ivy.array([[[-8.],
        [-1.]]]), 
grad = []
