<a href="https://colab.research.google.com/github/Kacper-W-Kozdon/notebook-testing-ivy/blob/main/Testing_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import tensorflow as tf

In [2]:
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([[5, 6], [7, 8]])
print(a.reshape(b.shape))
print(torch.reshape(a, b.shape))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [3]:
def gather_old(
    params: torch.Tensor,
    indices: torch.Tensor,
    /,
    *,
    axis: int = -1,
    batch_dims: int = 0,
    out: torch.Tensor = None,
) -> torch.Tensor:
    axis %= len(params.shape)
    batch_dims %= len(params.shape)
    result = []
    if batch_dims == 0:


      print(params.shape, indices.shape, params.shape < indices.shape, params.dim(), indices.dim())
      dim_diff = params.dim() - indices.dim()
      if dim_diff > 0:
        params_squeezed = params
        for d in range(dim_diff):
          params_squeezed.squeeze(-1)
        result = torch.take(
              params_squeezed, indices.long(), out=None)
        print("res: ", result)

        print("shape: ", (params.shape[:axis] + indices.shape[batch_dims:]
                                + params.shape[axis + 1 :]))
        for d in range(dim_diff):
          result = result.expand((params.shape[:axis] + indices.shape[batch_dims:]
                                + params.shape[axis + 1 :]))

        print("reshaped result: ", result)
      else:
        result = torch.take(
              params, indices.long(), out=None)
        print("else res: ", result)
        print("shape: ", (params.shape[:axis] + indices.shape[batch_dims:]
                                + params.shape[axis + 1 :]))
        result = result.reshape((params.shape[:axis] + indices.shape[batch_dims:]
                                + params.shape[axis + 1 :])
                                )

      print([*params.shape[0:batch_dims], *result.shape[1:]], (params.shape[:axis] + indices.shape[batch_dims:]
                              + params.shape[axis + 1 :]), result, params.shape, indices.shape, params.shape > indices.shape, params.shape == indices.shape
            )

    else:
        params_slices = torch.unbind(params, axis=0)
        indices_slices = torch.unbind(indices, axis=0)
        for b in range(batch_dims):
            if b == 0:
                zip_list = [(p, i) for p, i in zip(params_slices, indices_slices)]
            else:
                zip_list = [
                    (p, i) for z in [zip(p1, i1) for p1, i1 in zip_list] for p, i in z
                ]
        for z in zip_list:
            p, i = z
            print(p.shape, i.reshape((-1, )).shape)
            r = torch.gather(
                p, (axis - batch_dims), torch.reshape(i.long(), (-1, )),
                sparse_grad=False, out=None
            )

            result.append(r)
        result = torch.stack(result)
        #result = torch.cat(result, dim=0)
        print("shape: ", (params.shape[:axis] + indices.shape[batch_dims:]
                                + params.shape[axis + 1 :]))
        result = result.reshape((params.shape[:axis] + indices.shape[batch_dims:]
                                + params.shape[axis + 1 :])
                                )
    return result

In [13]:
def gather(
    params: torch.Tensor,
    indices: torch.Tensor,
    /,
    *,
    axis: int = -1,
    batch_dims: int = 0,
    out: torch.Tensor = None,
) -> torch.Tensor:
    axis %= len(params.shape)
    axis = abs(len(params.shape) + axis) if axis < 0 else axis
    print(f"AXIS: {axis}")
    batch_dims %= len(params.shape)
    result = []

    def expand_p_i(params, indices):
        ind_dim_helper_table = [1 for dim in list(indices.shape)]
        ind_singleton_dims = torch.Size(ind_dim_helper_table)
        param_singleton_dims_table = [1 for dim in list(params.shape)]
        param_singleton_dims = torch.Size(param_singleton_dims_table)
        print("INDICES SHAPE: ", indices.shape)
        print("PARAMS SHAPE: ", params.shape)
        print(f"SINGLETON_DIMS: {param_singleton_dims}, {ind_singleton_dims}")
        print("RESHAPE SHAPE: ", param_singleton_dims[:axis]
                                     + indices.shape[batch_dims:]
                                     + param_singleton_dims[axis + 1:], "\n",
                                    params.shape[:axis]
                                   + max([ind_singleton_dims[batch_dims:batch_dims + 1], params.shape[axis:axis + 1]]) + ind_singleton_dims[batch_dims + 1:]
                                   + params.shape[axis + 1:])
        print(param_singleton_dims[:axis],
                                      indices.shape[batch_dims:],
                                      param_singleton_dims[axis + 1:], batch_dims)
        params_ex = params.reshape((params.shape[:axis]
                                   + max([ind_singleton_dims[batch_dims:batch_dims + 1], params.shape[axis:axis + 1]]) + ind_singleton_dims[batch_dims + 1:]
                                   + params.shape[axis + 1:])) if (indices.dim() - batch_dims <= 1 or params.dim() - axis <= 1) else \
                    params.reshape(params.shape[:axis]
                                   + ind_singleton_dims[batch_dims + 1:]
                                   + params.shape[axis + 1:])
        indices_ex = indices if (indices.dim() - batch_dims <= 1 or params.dim() - axis <= 1) else \
                    indices.reshape(param_singleton_dims[:axis]
                                     + indices.shape[batch_dims:]
                                     + param_singleton_dims[axis + 1:])

        print("FINAL SHAPE: ", params.shape[:axis]
                                         + indices.shape[batch_dims:]
                                         + params.shape[axis + 1:], params.shape[axis:] + indices.shape[batch_dims:] + params.shape[axis + 1:] >= params_ex.shape)

        if (params.shape[:axis]
           + indices.shape[batch_dims:]
           + params.shape[axis + 1:]) >= params_ex.shape:
            params_ex = params_ex.expand(params.shape[:axis]
                                         + indices.shape[batch_dims:]
                                         + params.shape[axis + 1:])
        if (params.shape[:axis]
           + indices.shape[batch_dims:]
           + params.shape[axis + 1:]) >= indices_ex.shape:
            indices_ex = indices_ex.expand(params.shape[:axis]
                                           + indices.shape[batch_dims:]
                                           + params.shape[axis + 1:])
        print("EXPANDED SHAPES: ", params_ex.shape, indices_ex.shape)
        return params_ex, indices_ex
    if batch_dims == 0:
        dim_diff = params.dim() - indices.dim()
        if dim_diff != 0:
            params_expanded, indices_expanded = expand_p_i(params, indices)
            result = torch.gather(
                                    params_expanded, axis,
                                    indices_expanded.long(),
                                    sparse_grad=False, out=out
                                 )
            return result
        else:
            params_expanded, indices_expanded = expand_p_i(params, indices)
            result = torch.gather(
                params_expanded, axis, indices_expanded.long(), sparse_grad=False, out=out)

    else:
        params_slices = torch.unbind(params, axis=0) if params.dim() > 1 else params
        indices_slices = torch.unbind(indices, axis=0) if indices.dim() > 1 else indices
        print(f"SLICES: {params_slices}, {indices_slices}")
        for b in range(batch_dims):
            if b == 0:
                zip_list = [(p, i) for
                            p, i in
                            zip(params_slices, indices_slices)
                            ]
            else:
                zip_list = [
                           (p, i) for z in [zip(p1, i1) for p1, i1 in zip_list]
                           for p, i in z
                            ]
        for z in zip_list:
            p, i = z
            dim_diff = p.dim() - i.dim()
            p_expanded = p
            i_expanded = i
            if dim_diff != 0:
              p_expanded, i_expanded = expand_p_i(p, i)
            print("p, i shapes: ", p_expanded.shape, i_expanded.shape)
            r = torch.gather(
                             p_expanded, (axis - batch_dims),
                             i_expanded.long(),
                             sparse_grad=False, out=None
                            )

            result.append(r)
        result = torch.stack(result)
        result = result.reshape(params.shape[:axis] + max(indices.shape[batch_dims:], torch.Size([1])) + params.shape[axis + 1:])
        print("FINAL RES SHAPE: ", result.shape, params.shape[:axis], indices.shape[batch_dims:], params.shape[axis + 1:])


    return result

In [ ]:
params = torch.tensor([[-1.],
                 [ 1.],
                 [ 1.]])

indices = torch.tensor([[[0],
                  [0]],

                 [[0],
                  [0]],

                 [[0],
                  [0]]])

paramstf = tf.constant([[-1.],
                 [ 1.],
                 [ 1.]])

indicestf = tf.constant([[[0],
                  [0]],

                 [[0],
                  [0]],

                 [[0],
                  [0]]])

axis = 1
batch_dims = 1

print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
torch_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor)
tf_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
print()
print(tf_tensor == torch_to_tf)

tf:  tf.Tensor(
[[[-1.]
  [-1.]]

 [[ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]]], shape=(3, 2, 1), dtype=float32)


AXIS: 1
SLICES: (tensor([-1.]), tensor([1.]), tensor([1.])), (tensor([[0],
        [0]]), tensor([[0],
        [0]]), tensor([[0],
        [0]]))
INDICES SHAPE:  torch.Size([2, 1])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([1, 1])
torch.Size([1]) torch.Size([1]) torch.Size([]) 1
FINAL SHAPE:  torch.Size([1, 1]) True
EXPANDED SHAPES:  torch.Size([1, 1]) torch.Size([2, 1])
p, i shapes:  torch.Size([1, 1]) torch.Size([2, 1])
INDICES SHAPE:  torch.Size([2, 1])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([1, 1])
torch.Size([1]) torch.Size([1]) torch.Size([]) 1
FINAL SHAPE:  torch.Size([1, 1]) True
EXPANDED SHAPES:  torch.Size([1, 1]) torch.Size([2, 1])
p, i shapes:  torch.Size([1, 1]) torch.Size([2, 1])
INDICES SHA

In [ ]:
params = torch.tensor([0])

indices = torch.tensor([0, 0])

paramstf = tf.constant([0])

indicestf = tf.constant([0, 0])

axis = 0
batch_dims = 0

print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

tf:  tf.Tensor([0 0], shape=(2,), dtype=int32)


AXIS: 0
INDICES SHAPE:  torch.Size([2])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([2]) 
 torch.Size([1])
torch.Size([]) torch.Size([2]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([2]) True
EXPANDED SHAPES:  torch.Size([2]) torch.Size([2])
torch:  tensor([0, 0])
AXIS: 0
INDICES SHAPE:  torch.Size([2])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([2]) 
 torch.Size([1])
torch.Size([]) torch.Size([2]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([2]) True
EXPANDED SHAPES:  torch.Size([2]) torch.Size([2])
torch_to_tf:  tf.Tensor([0 0], shape=(2,), dtype=int32)

tf.Tensor([ True  True], shape=(2,), dtype=bool)


In [ ]:
params = torch.tensor([-1])

indices = torch.tensor([[0]])

paramstf = tf.constant([-1])

indicestf = tf.constant([[0]])

axis = 0
batch_dims = 0

print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

tf:  tf.Tensor([[-1]], shape=(1, 1), dtype=int32)


AXIS: 0
INDICES SHAPE:  torch.Size([1, 1])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([1, 1])
torch.Size([]) torch.Size([1, 1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([1, 1]) True
EXPANDED SHAPES:  torch.Size([1, 1]) torch.Size([1, 1])
torch:  tensor([[-1]])
AXIS: 0
INDICES SHAPE:  torch.Size([1, 1])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([1, 1])
torch.Size([]) torch.Size([1, 1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([1, 1]) True
EXPANDED SHAPES:  torch.Size([1, 1]) torch.Size([1, 1])
torch_to_tf:  tf.Tensor([[-1]], shape=(1, 1), dtype=int32)

tf.Tensor([[ True]], shape=(1, 1), dtype=bool)


In [ ]:
params = torch.tensor([[-1]])

indices = torch.tensor([0])

paramstf = tf.constant([[-1]])

indicestf = tf.constant([0])

axis = 0
batch_dims = 0

print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

tf:  tf.Tensor([[-1]], shape=(1, 1), dtype=int32)


AXIS: 0
INDICES SHAPE:  torch.Size([1])
PARAMS SHAPE:  torch.Size([1, 1])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([1, 1])
torch.Size([]) torch.Size([1]) torch.Size([1]) 0
FINAL SHAPE:  torch.Size([1, 1]) True
EXPANDED SHAPES:  torch.Size([1, 1]) torch.Size([1, 1])
torch:  tensor([[-1]])
AXIS: 0
INDICES SHAPE:  torch.Size([1])
PARAMS SHAPE:  torch.Size([1, 1])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([1, 1])
torch.Size([]) torch.Size([1]) torch.Size([1]) 0
FINAL SHAPE:  torch.Size([1, 1]) True
EXPANDED SHAPES:  torch.Size([1, 1]) torch.Size([1, 1])
torch_to_tf:  tf.Tensor([[-1]], shape=(1, 1), dtype=int32)

tf.Tensor([[ True]], shape=(1, 1), dtype=bool)


In [ ]:
params = torch.tensor([0])

indices = torch.tensor([0])

paramstf = tf.constant([0])

indicestf = tf.constant([0])

axis = 0
batch_dims = 0

print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

tf:  tf.Tensor([0], shape=(1,), dtype=int32)


AXIS: 0
INDICES SHAPE:  torch.Size([1])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1]) 
 torch.Size([1])
torch.Size([]) torch.Size([1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([1]) True
EXPANDED SHAPES:  torch.Size([1]) torch.Size([1])
torch:  tensor([0])
AXIS: 0
INDICES SHAPE:  torch.Size([1])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1]) 
 torch.Size([1])
torch.Size([]) torch.Size([1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([1]) True
EXPANDED SHAPES:  torch.Size([1]) torch.Size([1])
torch_to_tf:  tf.Tensor([0], shape=(1,), dtype=int32)

tf.Tensor([ True], shape=(1,), dtype=bool)


In [ ]:
params = torch.tensor([[0],
                 [0]])

indices = torch.tensor([0])

paramstf = tf.constant([[0],
                 [0]])

indicestf = tf.constant([0])

axis = 1
batch_dims = 0


print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

tf:  tf.Tensor(
[[0]
 [0]], shape=(2, 1), dtype=int32)


AXIS: 1
INDICES SHAPE:  torch.Size([1])
PARAMS SHAPE:  torch.Size([2, 1])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([2, 1])
torch.Size([1]) torch.Size([1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([2, 1]) False
EXPANDED SHAPES:  torch.Size([2, 1]) torch.Size([2, 1])
torch:  tensor([[0],
        [0]])
AXIS: 1
INDICES SHAPE:  torch.Size([1])
PARAMS SHAPE:  torch.Size([2, 1])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([2, 1])
torch.Size([1]) torch.Size([1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([2, 1]) False
EXPANDED SHAPES:  torch.Size([2, 1]) torch.Size([2, 1])
torch_to_tf:  tf.Tensor(
[[0]
 [0]], shape=(2, 1), dtype=int32)

tf.Tensor(
[[ True]
 [ True]], shape=(2, 1), dtype=bool)


In [ ]:
params = torch.tensor([[-13712,  25013, -11631,  -2072,  -7720, -29788, -27294]])

indices = torch.tensor([3, 4, 1])

paramstf = tf.constant([[-13712,  25013, -11631,  -2072,  -7720, -29788, -27294]])

indicestf = tf.constant([3, 4, 1])

axis = 1
batch_dims = 0

print(f"BATCH DIMS: {batch_dims}")
print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

BATCH DIMS: 0
tf:  tf.Tensor([[-2072 -7720 25013]], shape=(1, 3), dtype=int32)


AXIS: 1
INDICES SHAPE:  torch.Size([3])
PARAMS SHAPE:  torch.Size([1, 7])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1, 3]) 
 torch.Size([1, 1])
torch.Size([1]) torch.Size([3]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([1, 3]) True
EXPANDED SHAPES:  torch.Size([1, 7]) torch.Size([1, 3])
torch:  tensor([[-2072, -7720, 25013]])
AXIS: 1
INDICES SHAPE:  torch.Size([3])
PARAMS SHAPE:  torch.Size([1, 7])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1, 3]) 
 torch.Size([1, 1])
torch.Size([1]) torch.Size([3]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([1, 3]) True
EXPANDED SHAPES:  torch.Size([1, 7]) torch.Size([1, 3])
torch_to_tf:  tf.Tensor([[-2072 -7720 25013]], shape=(1, 3), dtype=int32)

tf.Tensor([[ True  True  True]], shape=(1, 3), dtype=bool)


In [ ]:
params = torch.tensor([[-1, -1]])

indices = torch.tensor([0])

paramstf = tf.constant([[-1, -1]])

indicestf = tf.constant([0])

axis = 0
batch_dims = 0



print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

tf:  tf.Tensor([[-1 -1]], shape=(1, 2), dtype=int32)


AXIS: 0
INDICES SHAPE:  torch.Size([1])
PARAMS SHAPE:  torch.Size([1, 2])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([1, 2])
torch.Size([]) torch.Size([1]) torch.Size([1]) 0
FINAL SHAPE:  torch.Size([1, 2]) True
EXPANDED SHAPES:  torch.Size([1, 2]) torch.Size([1, 2])
torch:  tensor([[-1, -1]])
AXIS: 0
INDICES SHAPE:  torch.Size([1])
PARAMS SHAPE:  torch.Size([1, 2])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([1, 2])
torch.Size([]) torch.Size([1]) torch.Size([1]) 0
FINAL SHAPE:  torch.Size([1, 2]) True
EXPANDED SHAPES:  torch.Size([1, 2]) torch.Size([1, 2])
torch_to_tf:  tf.Tensor([[-1 -1]], shape=(1, 2), dtype=int32)

tf.Tensor([[ True  True]], shape=(1, 2), dtype=bool)


In [ ]:
params = torch.tensor([[-1]])

indices = torch.tensor([[0]])

paramstf = tf.constant([[-1]])

indicestf = tf.constant([[0]])

axis = 0
batch_dims = 0


print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

tf:  tf.Tensor([[[-1]]], shape=(1, 1, 1), dtype=int32)


AXIS: 0
INDICES SHAPE:  torch.Size([1, 1])
PARAMS SHAPE:  torch.Size([1, 1])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([1, 1, 1]) 
 torch.Size([1, 1, 1])
torch.Size([]) torch.Size([1, 1]) torch.Size([1]) 0
FINAL SHAPE:  torch.Size([1, 1, 1]) True
EXPANDED SHAPES:  torch.Size([1, 1, 1]) torch.Size([1, 1, 1])
torch:  tensor([[[-1]]])
AXIS: 0
INDICES SHAPE:  torch.Size([1, 1])
PARAMS SHAPE:  torch.Size([1, 1])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([1, 1, 1]) 
 torch.Size([1, 1, 1])
torch.Size([]) torch.Size([1, 1]) torch.Size([1]) 0
FINAL SHAPE:  torch.Size([1, 1, 1]) True
EXPANDED SHAPES:  torch.Size([1, 1, 1]) torch.Size([1, 1, 1])
torch_to_tf:  tf.Tensor([[[-1]]], shape=(1, 1, 1), dtype=int32)

tf.Tensor([[[ True]]], shape=(1, 1, 1), dtype=bool)


In [ ]:
a = torch.tensor([[1]])
print(a.reshape((1, 1, 1)))

In [ ]:
params = torch.tensor([[-1], [-1], [-1]])

indices = torch.tensor([1])

paramstf = tf.constant([[-1], [-1], [-1]])

indicestf = tf.constant([1])

axis = 0
batch_dims = 0
print(indices.unsqueeze(-1).unsqueeze(-1))
print(params.squeeze(-1))
print(params.dim(), indices.dim())
print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

tensor([[[1]]])
tensor([-1, -1, -1])
2 1
tf:  tf.Tensor([[-1]], shape=(1, 1), dtype=int32)


AXIS: 0
INDICES SHAPE:  torch.Size([1])
PARAMS SHAPE:  torch.Size([3, 1])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([1, 1])
torch.Size([]) torch.Size([1]) torch.Size([1]) 0
FINAL SHAPE:  torch.Size([1, 1]) True
EXPANDED SHAPES:  torch.Size([3, 1]) torch.Size([1, 1])
torch:  tensor([[-1]])
AXIS: 0
INDICES SHAPE:  torch.Size([1])
PARAMS SHAPE:  torch.Size([3, 1])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([1, 1])
torch.Size([]) torch.Size([1]) torch.Size([1]) 0
FINAL SHAPE:  torch.Size([1, 1]) True
EXPANDED SHAPES:  torch.Size([3, 1]) torch.Size([1, 1])
torch_to_tf:  tf.Tensor([[-1]], shape=(1, 1), dtype=int32)

tf.Tensor([[ True]], shape=(1, 1), dtype=bool)


In [ ]:
torch.gather(torch.tensor([[-1], [-1], [-1]]), 0, torch.tensor([[1]]))

In [ ]:
params = torch.tensor([[0], [0], [1]])

indices = torch.tensor([0])

paramstf = tf.constant([[0], [0], [1]])

indicestf = tf.constant([0])

axis = 0
batch_dims = 1

print(params.dim(), indices.dim())
print(paramstf.shape[:axis] + indicestf.shape[batch_dims:] + paramstf.shape[axis + 1:])
print(params.shape[:axis] + indices.shape[batch_dims:] + params.shape[axis + 1:])

print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

2 1
(1,)
torch.Size([1])
tf:  tf.Tensor([[0]], shape=(1, 1), dtype=int32)


AXIS: 0
SLICES: (tensor([0]), tensor([0]), tensor([1])), tensor([0])
INDICES SHAPE:  torch.Size([])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([])
RESHAPE SHAPE:  torch.Size([]) 
 torch.Size([])
torch.Size([]) torch.Size([]) torch.Size([]) 1
FINAL SHAPE:  torch.Size([]) True
EXPANDED SHAPES:  torch.Size([1]) torch.Size([])
p, i shapes:  torch.Size([1]) torch.Size([])
FINAL RES SHAPE:  torch.Size([1, 1]) torch.Size([]) torch.Size([]) torch.Size([1])
torch:  tensor([[0]])
AXIS: 0
SLICES: (tensor([0]), tensor([0]), tensor([1])), tensor([0])
INDICES SHAPE:  torch.Size([])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([])
RESHAPE SHAPE:  torch.Size([]) 
 torch.Size([])
torch.Size([]) torch.Size([]) torch.Size([]) 1
FINAL SHAPE:  torch.Size([]) True
EXPANDED SHAPES:  torch.Size([1]) torch.Size([])
p, i shapes:  torch.Size([1]) torch.Size([])
FINAL RES SHAPE

In [ ]:
params = torch.tensor([[0], [1]])

indices = torch.tensor([[0]])

paramstf = tf.constant([[0], [1]])

indicestf = tf.constant([[0]])



axis = 1
batch_dims = 0
print(torch.gather(params, axis, indices))
print(params.shape)
print(indices.expand((indices.shape[0], params.shape[-1 - axis])))
print(torch.gather(params, axis, indices))
print(params.dim(), indices.dim())
print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

tensor([[0]])
torch.Size([2, 1])
tensor([[0, 0]])
tensor([[0]])
2 2
tf:  tf.Tensor(
[[[0]]

 [[1]]], shape=(2, 1, 1), dtype=int32)


AXIS: 1
INDICES SHAPE:  torch.Size([1, 1])
PARAMS SHAPE:  torch.Size([2, 1])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([1, 1, 1]) 
 torch.Size([2, 1, 1])
torch.Size([1]) torch.Size([1, 1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([2, 1, 1]) False
EXPANDED SHAPES:  torch.Size([2, 1, 1]) torch.Size([2, 1, 1])
torch:  tensor([[[0]],

        [[1]]])
AXIS: 1
INDICES SHAPE:  torch.Size([1, 1])
PARAMS SHAPE:  torch.Size([2, 1])
SINGLETON_DIMS: torch.Size([1, 1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([1, 1, 1]) 
 torch.Size([2, 1, 1])
torch.Size([1]) torch.Size([1, 1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([2, 1, 1]) False
EXPANDED SHAPES:  torch.Size([2, 1, 1]) torch.Size([2, 1, 1])
torch_to_tf:  tf.Tensor(
[[[0]]

 [[1]]], shape=(2, 1, 1), dtype=int32)

tf.Tensor(
[[[ True]]

 [[ True]]], shape=(2, 1, 1), d

In [ ]:
axis = 1
batch_dims = 0

params = torch.tensor([[[0], [2]]])

indices = torch.tensor([[[0], [0]], [[0], [0]]])
print("xxx: ", params.shape[:2] + indices.shape + params.shape[2 + 1:])
#params = params.expand((1, 2, 2))
#params = params.unsqueeze(-1).unsqueeze(-1)
params = params.expand(params.shape[:axis] + indices.shape + params.shape[axis + 1:])
print("params shape: ", params.shape)
indices = indices.unsqueeze(0).unsqueeze(2)
indices = indices.expand(params.shape)

paramstf = tf.constant([[[0], [2]]])

indicestf = tf.constant([[[0], [0]], [[0], [0]]])
print(paramstf.shape, indicestf.shape)

print(torch.gather(params, axis, indices))
print(tf.gather(paramstf, indicestf, axis, batch_dims = batch_dims))

xxx:  torch.Size([1, 2, 2, 2, 1])


RuntimeError: ignored

In [ ]:
a = torch.tensor([[1, 2]])
a.shape
a0 = a.expand((3, 3, 2))
a = a0.reshape((3, 3, 1, 2))
a = a.expand((3, 3, 2, 2))
ai0 = torch.ones((3, 2))
ai = ai0.reshape((1, 3, 2, 1))
ai = ai.expand((3, 3, 2, 2))

b = [1 for dim in list(a.shape)]
c = torch.Size(b)
d = torch.ones(c)

restorch = torch.gather(a, 1, ai.long())
torch_to_tf_a = tf.convert_to_tensor(a0, dtype = "int32")
torch_to_tf_ai = tf.convert_to_tensor(ai0, dtype = "int32")
print(torch_to_tf_a.shape, torch_to_tf_ai.shape)
restf = tf.gather(torch_to_tf_a, torch_to_tf_ai, axis = 1, batch_dims = 0)
print(restf)
print()
print(restorch.shape)
restf == tf.convert_to_tensor(restorch, dtype = "int32")


(3, 3, 2) (3, 2)
tf.Tensor(
[[[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]


 [[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]


 [[[1 2]
   [1 2]]

  [[1 2]
   [1 2]]

  [[1 2]
   [1 2]]]], shape=(3, 3, 2, 2), dtype=int32)

torch.Size([3, 3, 2, 2])


<tf.Tensor: shape=(3, 3, 2, 2), dtype=bool, numpy=
array([[[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]]])>

In [ ]:
params = torch.tensor([1])

indices = torch.tensor([[0], [0]])

paramstf = tf.constant([1])

indicestf = tf.constant([[0], [0]])

axis = -1
batch_dims = 0

print(params.shape)
print(indices.expand((indices.shape[0], params.shape[-1 - axis])))
print(params.shape[:axis] , indices.shape[batch_dims:] , params.shape[axis + 1:])
print(params.dim(), indices.dim())
print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
print(tf_tensor == tf.convert_to_tensor(torch_tensor, dtype = "int32"))
print("torch_to_tf: ", torch_to_tf)
print()

torch.Size([1])
tensor([[0],
        [0]])
torch.Size([]) torch.Size([2, 1]) torch.Size([1])
1 2
tf:  tf.Tensor(
[[1]
 [1]], shape=(2, 1), dtype=int32)


AXIS: 0
INDICES SHAPE:  torch.Size([2, 1])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([2, 1]) 
 torch.Size([1, 1])
torch.Size([]) torch.Size([2, 1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([2, 1]) True
EXPANDED SHAPES:  torch.Size([2, 1]) torch.Size([2, 1])
torch:  tensor([[1],
        [1]])
AXIS: 0
INDICES SHAPE:  torch.Size([2, 1])
PARAMS SHAPE:  torch.Size([1])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([2, 1]) 
 torch.Size([1, 1])
torch.Size([]) torch.Size([2, 1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([2, 1]) True
EXPANDED SHAPES:  torch.Size([2, 1]) torch.Size([2, 1])
tf.Tensor(
[[ True]
 [ True]], shape=(2, 1), dtype=bool)
torch_to_tf:  tf.Tensor(
[[[0]]

 [[1]]], shape=(2, 1, 1), dtype=int32)



In [ ]:
a = torch.tensor([[[1]]])
b = torch.tensor([-1, -1, -1])
axis = 0
batch_dims = 0
print(a.shape, b.shape)
print(a.reshape((1, 1, 1, 1)))
print(a.shape[:axis], b.shape, a.shape[axis + 1:])

a = a.expand((a.shape[:axis] + b.shape + a.shape[axis + 1:]))
print(a)

In [14]:
params = torch.tensor([0,
                 0])

indices = torch.tensor([[0]])

paramstf = tf.constant([0,
                 0])

indicestf = tf.constant([[0]])

axis = 0
batch_dims = 0


print("tf: ", tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims))
print()
print()
print("torch: ", gather(params, indices, axis = axis, batch_dims = batch_dims))
tf_tensor = tf.gather(paramstf, indicestf, axis = axis, batch_dims = batch_dims)
torch_tensor = gather(params, indices, axis = axis, batch_dims = batch_dims)
torch_to_tf = tf.convert_to_tensor(torch_tensor, dtype = "int32")
print("torch_to_tf: ", torch_to_tf)
print()
print(tf_tensor == torch_to_tf)

tf:  tf.Tensor([[0]], shape=(1, 1), dtype=int32)


AXIS: 0
INDICES SHAPE:  torch.Size([1, 1])
PARAMS SHAPE:  torch.Size([2])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([2, 1])
torch.Size([]) torch.Size([1, 1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([1, 1]) True
EXPANDED SHAPES:  torch.Size([2, 1]) torch.Size([1, 1])
torch:  tensor([[0]])
AXIS: 0
INDICES SHAPE:  torch.Size([1, 1])
PARAMS SHAPE:  torch.Size([2])
SINGLETON_DIMS: torch.Size([1]), torch.Size([1, 1])
RESHAPE SHAPE:  torch.Size([1, 1]) 
 torch.Size([2, 1])
torch.Size([]) torch.Size([1, 1]) torch.Size([]) 0
FINAL SHAPE:  torch.Size([1, 1]) True
EXPANDED SHAPES:  torch.Size([2, 1]) torch.Size([1, 1])
torch_to_tf:  tf.Tensor([[0]], shape=(1, 1), dtype=int32)

tf.Tensor([[ True]], shape=(1, 1), dtype=bool)


In [ ]:
a = torch.tensor([0])
print(a.dim())
a = torch.tensor([[0]])
print(a.dim())

1
2
