<a href="https://colab.research.google.com/github/Kacper-W-Kozdon/notebook-testing-ivy/blob/main/testing_ivy_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import shutil

In [1]:
!pip install paddlepaddle

In [2]:
import torch as torch
import paddle as paddle
import tensorflow as tf

In [9]:
!git clone -b core_matrix_norm https://github.com/Kacper-W-Kozdon/ivy.git

Cloning into 'ivy'...
remote: Enumerating objects: 188219, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 188219 (delta 2), reused 0 (delta 0), pack-reused 188209
Receiving objects: 100% (188219/188219), 163.92 MiB | 19.07 MiB/s, done.
Resolving deltas: 100% (151636/151636), done.


In [11]:
import ivy

In [6]:
!pip install ivy
import ivy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 31.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 19.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.0/756.0 kB 48.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 73.7 MB/s eta 0:00:00
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.0.7
    Uninstalling urllib3-2.0.7:
      Successfully uninstalled urllib3-2.0.7


In [ ]:
ivy.set_backend("paddle")
x = ivy.native_array([[[-1.], [-1.]]], dtype = "float32")
dtype = "float64"
x = x.astype(dtype)
keepdims = False
ord = -2
axis = (0, 2)

paddle_matrix_norm = ivy.linalg.matrix_norm(x, keepdims=keepdims, ord=ord, axis=axis)
def func_paddle(x):
  return ivy.linalg.matrix_norm(x, keepdims=keepdims, ord=ord, axis=axis)
print(func_paddle(x))
ret, grad = ivy.execute_with_gradients(func_paddle, x, retain_grads=True)
print(grad)

ivy.array([1., 1.])
[]


In [16]:
ivy.set_backend("torch")
x = ivy.native_array([[[-1.], [-1.]]], dtype = "float32")
dtype = torch.float64
keepdims = False
ord = -2
axis = (0, 2)

torch_matrix_norm = ivy.linalg.matrix_norm(x, keepdims=keepdims, dtype=dtype, ord=ord, axis=axis)
def func_torch(x):
  return ivy.linalg.matrix_norm(
      x, keepdims=keepdims, axis=axis, ord=ord, dtype=dtype)
print(func_torch(x))
ret, grad = ivy.execute_with_gradients(func_torch, x, retain_grads=True)
print(ret, grad)

ivy.array([1., 1.])
ivy.array([1., 1.]) []


In [32]:
ivy.set_backend("torch")
x = ivy.native_array([[[-2.], [-2.]]], dtype = "float32")
dtype = torch.float64
keepdims = False
ord = -2
axis = (0, 2)
x.requires_grad_(True)
def func_torch(x):
  return x**2
print(func_torch(x))
ret, grad = ivy.execute_with_gradients(func_torch, x, retain_grads=True)
print(ret, grad)

tensor([[[4.],
         [4.]]], grad_fn=<PowBackward0>)
ivy.array([[[4.],
        [4.]]]) []


In [30]:
ivy.set_backend("tensorflow")
x = ivy.native_array([[[-1.], [-1.]]], dtype = "float32")
dtype = tf.float64
keepdims = False
ord = -2
axis = (0, 2)

torch_matrix_norm = ivy.linalg.matrix_norm(x, keepdims=keepdims, dtype=dtype, ord=ord, axis=axis)
def func_tf(x):
  return ivy.linalg.matrix_norm(x, keepdims=keepdims, axis=axis, ord=ord, dtype=dtype)
print(func_tf(x))
ret, grad = ivy.execute_with_gradients(func_tf, x, retain_grads=True)
print(ret, grad)

ivy.array([1., 1.])
ivy.array([1., 1.]) ivy.array([[[-1.],
        [-1.]]])


In [31]:
ivy.set_backend("tensorflow")
x = ivy.native_array([[[-1.], [-1.]]], dtype = "float32")
dtype = tf.float64
keepdims = False
ord = -2
axis = (0, 2)

torch_matrix_norm = ivy.linalg.matrix_norm(x, keepdims=keepdims, dtype=dtype, ord=ord, axis=axis)
def func_tf(x):
  return x**2
print(func_tf(x))
ret, grad = ivy.execute_with_gradients(func_tf, x, retain_grads=True)
print(ret, grad)

tf.Tensor(
[[[1.]
  [1.]]], shape=(1, 2, 1), dtype=float32)
ivy.array([[[1.],
        [1.]]]) ivy.array([[[-2.],
        [-2.]]])


In [4]:

def func_torch_bfw():
  keepdims = False
  ord = 2
  axis = (0, 2)
  x = torch.tensor([[[-1.], [-1.]]])
  x.requires_grad_(True)
  y = torch.linalg.matrix_norm(x, ord=ord, keepdims=keepdims, axis=axis)
  print(y)
  y.backward(inputs=x, gradient=torch.ones(y.shape))
  return x.grad
func_torch_bfw()


tensor([1., 1.], grad_fn=<AmaxBackward0>)


tensor([[[-1.],
         [-1.]]])

In [ ]:
@tf.function
def example():
  x = tf.constant([[[-1.], [-1.]]])

  ord = 2
  axis = (0, 2)
  keepdims=False
  y = tf.linalg.norm(x, ord=ord, axis=axis, keepdims=keepdims)
  g = tf.gradients(y, x)
  return g
example()



[<tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
 array([[[-1.],
         [-1.]]], dtype=float32)>]

In [12]:
ivy.set_backend("paddle")
x = ivy.array([[[-1.], [-1.]]], dtype = "float32")
dtype = torch.float64
keepdims = False
ord = -2
axis = (0, 2)
func = lambda x: ivy.linalg.matrix_norm(x, keepdims=keepdims, ord=ord, axis=axis)
func_ret = ivy.execute_with_gradients(func, x, retain_grads=True)
print(func_ret)


(ivy.array([1., 1.]), [])
