<a href="https://colab.research.google.com/github/Kacper-W-Kozdon/notebook-testing-ivy/blob/main/testing_ivy_nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import shutil

In [2]:
!pip install torch
!pip install paddlepaddle
!pip install tensorflow

In [3]:
import torch as torch
import paddle as paddle
import tensorflow as tf

In [4]:
!git clone -b core_matrix_norm https://github.com/Kacper-W-Kozdon/ivy.git

fatal: destination path 'ivy' already exists and is not an empty directory.


In [5]:
!pip install ivy
import ivy

In [30]:
ivy.set_backend("paddle")
x = ivy.native_array([[[-1.]], [[-1.]]], dtype = "float32")
dtype = "float64"
x = x.astype(dtype)
keepdims = False
ord = -2
axis = (1, 2)

paddle_matrix_norm = ivy.linalg.matrix_norm(x, keepdims=keepdims, ord=ord, axis=axis)
def func_paddle(x):
  return ivy.linalg.matrix_norm(x, keepdims=keepdims, ord=ord, axis=axis)
print(func_paddle(x))
ret, grad = ivy.execute_with_gradients(func_paddle, x, retain_grads=True)
print(grad)

ivy.array([ 1., 33.])
[]


In [54]:
ivy.set_backend("torch")
x = ivy.native_array([[[-1.]], [[-1.]]], dtype = "float32")
dtype = torch.float64
keepdims = False
ord = -2
axis = (1, 2)

torch_matrix_norm = ivy.linalg.matrix_norm(x, keepdims=keepdims, dtype=dtype, ord=ord, axis=axis)
def func_torch(x):
  return ivy.linalg.matrix_norm(x, keepdims=keepdims, dtype=dtype, ord=ord, axis=axis)
print(func_torch(x))
ret, grad = ivy.execute_with_gradients(func_torch, x, retain_grads=True)
print(grad)

ivy.array([1., 1.])
[]


In [45]:

def func_torch_bfw():
  keepdims = False
  ord = -2
  axis = (1, 2)
  x = torch.tensor([[[-1.]], [[-1.]]])
  y = torch.linalg.matrix_norm(x, ord=ord, axis=axis, keepdims=keepdims)
  print(y)
  ret = torch.gradient(y)
  return ret
func_torch_bfw()


tensor([1., 1.])


(tensor([0., 0.]),)

In [9]:
@tf.function
def example():
  Ws = tf.constant(0.)
  bs = 2 * Ws
  cost = Ws + bs  # This is just an example. Please ignore the formulas.
  g = tf.gradients(cost, [Ws, bs])
  dCost_dW, dCost_db = g
  return dCost_dW, dCost_db
example()



(<tf.Tensor: shape=(), dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

In [10]:
x = ivy.array([[1, 4, 6], [2, 6, 9]])
func = lambda x: ivy.mean(ivy.square(x))
func_ret = ivy.execute_with_gradients(func, x, retain_grads=True)
print(func_ret)


(ivy.array(29.), ivy.array([[0.33333334, 1.33333337, 2.        ],
       [0.66666669, 2.        , 3.        ]]))
